export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST"
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS"
export const CREATE_TODO_FAIL = "CREATE_TODO_FAIL"

export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST"
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS"
export const EDIT_TODO_FAIL = "EDIT_TODO_FAIL"

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL"

export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST"
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS"
export const FETCH_TODO_FAIL = "FETCH_TODO_FAIL"

export const UPLOAD_TODO_REQUEST = "UPLOAD_TODO_REQUEST"
export const UPLOAD_TODO_SUCCESS = "UPLOAD_TODO_SUCCESS"
export const UPLOAD_TODO_FAIL = "UPLOAD_TODO_FAIL"


